
(define (domain partnr-rearrange)
  (:requirements :strips :equality)
  (:predicates
    (agent ?a)
    (object ?o)
    (furniture ?f)
    (receptacle ?r)
    (joint ?j)
    (room ?r)
    (container ?f)
    (has_faucet ?f)
    (at_faucet ?a ?f)
    (near ?a ?x)
    (at ?a ?r)
    (inroom ?x ?r)
    (on ?o ?f)
    (in ?o ?f)
    (holding ?a ?o)
    (handempty ?a)
    (open ?j)
    (closed ?j)
    (reachable ?a ?x)
    (powered_on ?o)
    (powered_off ?o)
    (filled ?o)
    (cleaned ?x)
  )

  (:action navigate
    :parameters (?a ?x ?r)
    :precondition (and (agent ?a) (room ?r) (inroom ?x ?r))
    :effect (and (at ?a ?r) (near ?a ?x) (at_faucet ?a ?x))
  )

  (:action pick
    :parameters (?a ?o ?r)
    :precondition (and (agent ?a) (object ?o) (room ?r)
                       (at ?a ?r) (inroom ?o ?r)
                       (handempty ?a) (reachable ?a ?o) (near ?a ?o))
    :effect (and (holding ?a ?o)
                 (not (handempty ?a))
                 (not (near ?a ?o)))
  )

  (:action place_on
    :parameters (?a ?o ?f ?r)
    :precondition (and (agent ?a) (object ?o) (furniture ?f) (room ?r)
                       (holding ?a ?o) (at ?a ?r) (inroom ?f ?r)
                       (reachable ?a ?f) (near ?a ?f)
                       (not (has_faucet ?f)))
    :effect (and (on ?o ?f)
                 (handempty ?a)
                 (not (holding ?a ?o))
                 (not (near ?a ?f)))
  )

  (:action place_in
    :parameters (?a ?o ?f ?r)
    :precondition (and (agent ?a) (object ?o) (furniture ?f) (room ?r)
                       (container ?f) (not (closed ?f))
                       (holding ?a ?o) (at ?a ?r) (inroom ?f ?r)
                       (reachable ?a ?f) (near ?a ?f))
    :effect (and (in ?o ?f)
                 (handempty ?a)
                 (not (holding ?a ?o))
                 (not (near ?a ?f)))
  )

  (:action open
    :parameters (?a ?j ?r)
    :precondition (and (agent ?a) (joint ?j) (room ?r)
                       (at ?a ?r) (inroom ?j ?r)
                       (closed ?j) (reachable ?a ?j) (near ?a ?j))
    :effect (and (open ?j)
                 (not (closed ?j))
                 (not (near ?a ?j)))
  )

  (:action close
    :parameters (?a ?j ?r)
    :precondition (and (agent ?a) (joint ?j) (room ?r)
                       (at ?a ?r) (inroom ?j ?r)
                       (open ?j) (reachable ?a ?j) (near ?a ?j))
    :effect (and (closed ?j)
                 (not (open ?j))
                 (not (near ?a ?j)))
  )

  (:action power_on
    :parameters (?a ?f ?r)
    :precondition (and (agent ?a) (furniture ?f) (room ?r)
                       (at ?a ?r) (inroom ?f ?r)
                       (reachable ?a ?f) (near ?a ?f))
    :effect (and (powered_on ?f)
                 (not (powered_off ?f))
                 (not (near ?a ?f)))
  )

  (:action power_off
    :parameters (?a ?f ?r)
    :precondition (and (agent ?a) (furniture ?f) (room ?r)
                       (at ?a ?r) (inroom ?f ?r)
                       (reachable ?a ?f) (near ?a ?f) (powered_on ?f))
    :effect (and (powered_off ?f)
                 (not (powered_on ?f))
                 (not (near ?a ?f)))
  )

  (:action power_on_object
    :parameters (?a ?o ?r)
    :precondition (and (agent ?a) (object ?o) (room ?r)
                       (at ?a ?r) (inroom ?o ?r)
                       (reachable ?a ?o) (near ?a ?o))
    :effect (and (powered_on ?o)
                 (not (powered_off ?o))
                 (not (near ?a ?o)))
  )

  (:action power_off_object
    :parameters (?a ?o ?r)
    :precondition (and (agent ?a) (object ?o) (room ?r)
                       (at ?a ?r) (inroom ?o ?r)
                       (reachable ?a ?o) (near ?a ?o) (powered_on ?o))
    :effect (and (powered_off ?o)
                 (not (powered_on ?o))
                 (not (near ?a ?o)))
  )

  (:action fill_held
    :parameters (?a ?o ?f ?r)
    :precondition (and (agent ?a) (object ?o) (room ?r)
                       (at ?a ?r) (holding ?a ?o)
                       (furniture ?f) (has_faucet ?f)
                       (near ?a ?f))
    :effect (and (filled ?o)
                 (not (near ?a ?f)))
  )

  (:action clean_object
    :parameters (?a ?o ?f ?r)
    :precondition (and (agent ?a) (object ?o) (furniture ?f) (room ?r)
                       (at ?a ?r) (holding ?a ?o)
                       (has_faucet ?f) (near ?a ?f))
    :effect (and (cleaned ?o)
                 (not (near ?a ?f)))
  )

  (:action clean_furniture
    :parameters (?a ?f ?r)
    :precondition (and (agent ?a) (furniture ?f) (room ?r)
                       (at ?a ?r) (inroom ?f ?r)
                       (reachable ?a ?f) (near ?a ?f))
    :effect (and (cleaned ?f)
                 (not (near ?a ?f)))
  )

  (:action pour
    :parameters (?a ?src ?tgt ?r)
    :precondition (and (agent ?a) (object ?src) (object ?tgt) (room ?r)
                       (holding ?a ?src) (filled ?src)
                       (at ?a ?r) (inroom ?tgt ?r)
                       (reachable ?a ?tgt) (near ?a ?tgt))
    :effect (and (filled ?tgt)
                 (not (near ?a ?tgt)))
  )
)
